### ISSUE TITLE
Is this supposed to be a port to Python 3.x?

### ISSUE THREAD

**Issue by jski3** [smop3/smop#2]
When I try running the 2.7 version using 3.x, it dies with:
`python run.py ~/rainflow_function.m
/home/jski/.local/lib/python3.9/site-packages/ply/lex.py:760: FutureWarning: Possible nested set at position 65
  c = re.compile('(?P<%s>%s)' % (fname, _get_regex(f)), self.reflags)
/home/jski/.local/lib/python3.9/site-packages/ply/lex.py:498: FutureWarning: Possible nested set at position 118
  lexre = re.compile(regex, reflags)
str
Traceback (most recent call last):
  File "/home/jski/smop/smop/main.py", line 66, in main
    G = resolve.resolve(stmt_list)
  File "/home/jski/smop/smop/resolve.py", line 54, in resolve
    u = G.node[n]["ident"]
AttributeError: 'DiGraph' object has no attribute 'node'
Errors: 1`
The important part is: **'DiGraph' object has no attribute 'node'** 
That happens in resolve.py. 
The only changes to resolve.py here are cosmetic?

**Comment by yangbo** [comment]
hi jski3, maybe you should run commands below before running smop:

```
git clone git@github.com:smop3/smop
cd smop3
pip install -e .
```

I can run smop in python3, so I think smop3 is for python3.
